# Generated by Django 4.2.7 on 2023-11-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='Место')),
                ('time_start', models.TimeField(verbose_name='Тайминг выполнения привычки')),
                ('action', models.CharField(max_length=150, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Полезная привычка')),
                ('periodicity', models.CharField(blank=True, choices=[('1', 'раз в 7 дней'), ('2', '2 раза в 7 дней'), ('3', '3 раза в 7 дней'), ('4', '4 раза в 7 дней'), ('5', '5 раз в 7 дней'), ('6', '6 раз в 7 дней'), ('7', '7 раз в 7 дней')], default=1, max_length=10, null=True, verbose_name='Периодичность: сколько раз в неделю')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('time_complete', models.IntegerField(verbose_name='Время на выполнение в сек')),
                ('is_published', models.BooleanField(blank=True, default=False, null=True, verbose_name='Опубликована')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
